# Docker image for frontend
FROM node:alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV VITE_BACKEND_URL=http://backend:3000
EXPOSE 80
CMD ["npm", "start"]


# FROM nginx:stable-alpine3.17-slim
# COPY --from=builder /app/dist /usr/share/nginx/html
# CMD ["nginx", "-g", "daemon off;"]
