version: "3"
services:
    recommendation:
        image: iddhi/smart-agriculture-system:recommendation-jammy-1.0.0
        ports:
            - "2000:2000"
        stdin_open: true
        tty: true
        networks:
            - models-driver

    frontend:
        image: iddhi/smart-agriculture-system:frontend-jammy-1.0.0
        ports:
            - "80:80"
        environment:
            - NODE_ENV=production
            - PORT=80
            - VITE_PORT=http://localhost:3000
        stdin_open: true
        tty: true

    backend:
        image: iddhi/smart-agriculture-system:backend-jammy-1.0.0
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
            - DB=${DB:-mongodb://admin:password@database:27017/agri_system}
            - RECOMMENDATION_URL=http://recommendation:2000
        depends_on:
            - database
        networks:
            - database-driver
            - models-driver
        stdin_open: true
        tty: true

    database:
        image: mongo:6.0.15-rc0-jammy
        ports:
            - "27017:27017"
        networks:
            - database-driver
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

networks:
    database-driver:
        driver: bridge
    models-driver:
        driver: bridge
