version: "3"
services:
    prediction:
        build: ./models/PricePrediction
        image: iddhi/smart-agriculture-system:prediction
        stdin_open: true
        tty: true
        networks:
            - models-driver
        depends_on:
            - backend
        command: ["python", "main.py"]

    recommendation:
        build: ./models/CropRecommendation
        image: iddhi/smart-agriculture-system:recommendation
        ports:
            - "2000:2000"
        stdin_open: true
        tty: true
        networks:
            - models-driver

    frontend:
        build: ./frontend
        image: iddhi/smart-agriculture-system:frontend
        ports:
            - "80:80"
        environment:
            - PORT=80
            - VITE_PORT=http://localhost:3000
        stdin_open: true
        tty: true
        networks:
            - web-gateway

    backend:
        build: ./backend
        image: iddhi/smart-agriculture-system:backend
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - DB=${DB:-mongodb://admin:password@database:27017/agri_system}
            - RECOMMENDATION_URL=http://recommendation:2000
            - EMAIL=testmail@gmail.com
            - PASSWORD=testpassword
        depends_on:
            - database
        networks:
            - database-driver
            - models-driver
            - web-gateway
        stdin_open: true
        tty: true

    database:
        image: mongo:6.0.15-rc0-jammy
        ports:
            - "27017:27017"
        networks:
            - database-driver
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - database-data:/data/db

volumes:
    database-data:

networks:
    database-driver:
        driver: bridge
    models-driver:
        driver: bridge
    web-gateway:
        driver: bridge
