version: "3"
services:
    frontend:
        build: ./frontend
        image: iddhi/smart-agriculture-system:frontend
        ports:
            - "5000:80"
        environment:
            - NODE_ENV=production
            - PORT=80
            - VITE_PORT=http://localhost:3000
        stdin_open: true
        tty: true

    backend:
        build: ./backend
        image: iddhi/smart-agriculture-system:backend
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
            - DB=${DB:-mongodb://admin:password@database:27017/librarysystem}
        depends_on:
            - database
        networks:
            - mern-app
        stdin_open: true
        tty: true

    database:
        image: mongo:6.0.15-rc0-jammy
        ports:
            - "27017:27017"
        networks:
            - mern-app
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

networks:
    mern-app:
        driver: bridge
