# run the app in a node container
FROM node:alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
ENV PORT=3000
EXPOSE ${PORT}
RUN npm install -g migrate-mongo
CMD migrate-mongo up && npm start