name: Create Docker Release Issue
on:
    pull_request:
        types: [opened]
        branches:
            - release

jobs:
    create-issue:
        name: Create Docker Release Pending Issue
        runs-on: ubuntu-latest
        steps:
            - name: Create Issue
              uses: actions/github-script@v7
              with:
                  script: |
                      const { data: issue } = await github.rest.issues.create({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          title: `Docker Release Pending: PR #${{ github.event.pull_request.number }}`,
                          body: `## 🚀 Docker Release Pending
                      
                      A pull request has been opened to the \`release\` branch and will trigger a Docker image build and publish once merged.
                      
                      **Pull Request Details:**
                      - **PR #${{ github.event.pull_request.number }}**: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
                      - **Author**: @${{ github.event.pull_request.user.login }}
                      - **Target Branch**: \`${{ github.event.pull_request.base.ref }}\`
                      - **Source Branch**: \`${{ github.event.pull_request.head.ref }}\`
                      
                      **What happens next:**
                      1. Once this PR is merged into the \`release\` branch, the Docker build workflow will automatically trigger
                      2. Docker images will be built and pushed to Docker Hub with appropriate versioning
                      3. If the merge commit includes a \`VERSION:\` prefix (e.g., \`VERSION: alpine-1.2.0\`), that version will be used
                      4. Otherwise, the patch version will be auto-incremented from the latest Docker Hub tag
                      
                      **Expected Docker Images:**
                      - \`iddhi/smart-agriculture-system:prediction-{version}\`
                      - \`iddhi/smart-agriculture-system:recommendation-{version}\`
                      - \`iddhi/smart-agriculture-system:frontend-{version}\`
                      - \`iddhi/smart-agriculture-system:backend-{version}\`
                      
                      ---
                      *This issue was automatically created when PR #${{ github.event.pull_request.number }} was opened to the release branch.*`,
                          labels: ['docker', 'release', 'automated']
                      });
                      
                      console.log(`Created issue #${issue.number}: ${issue.title}`);
                      console.log(`Issue URL: ${issue.html_url}`);
